// packages/react/src/components/CandidateSelection.tsx
import React from 'react'
import '../styles/CandidateSelection.scss'

interface CandidateSelectionProps {
  candidates: string[]
  onSelect: (index: number) => void
  onClose: () => void
}

const CandidateSelection: React.FC<CandidateSelectionProps> = ({ candidates, onSelect, onClose }) => {
  function getNumberCount(candidate: string) {
    const length = Array.from(candidate).length
    if (length >= 2 && length <= 3) {
      return 2
    } else if (length >= 4) {
      return 3
    }
    return 1
  }

  return (
    <div className="zhk-selection">
      <div className="zhk-selection__list">
        {candidates.map((candidate, index) => (
          <div key={candidate} className={`zhk-selection__text zhk-selection__text--span-${getNumberCount(candidate)}`} onClick={() => onSelect(index)}>
            {candidate}
          </div>
        ))}
      </div>
      <div className="zhk-selection__func">
        <button className="zhk-selection__func-btn" onClick={onClose}>
          返回
        </button>
      </div>
    </div>
  )
}

export default CandidateSelection

// packages/vue/src/components/CandidateSelection.vue
<script setup lang="ts">
import '../styles/CandidateSelection.scss'

defineProps<{ candidates: string[] }>()
const emit = defineEmits<{
  (e: 'select', index: number): void
  (e: 'close'): void
}>()

function selectCandidate(index: number) {
  emit('select', index)
}

function closeModal() {
  emit('close')
}

function getNumberCount(candidate: string) {
  const length = Array.from(candidate).length
  if (length >= 2 && length <= 3) {
    return 2
  } else if (length >= 4) {
    return 3
  }
  return 1
}
</script>

<template>
  <div class="zhk-selection">
    <div class="zhk-selection__list">
      <div
        v-for="(candidate, index) in candidates"
        :key="index"
        class="zhk-selection__text"
        :class="[`zhk-selection__text--span-${getNumberCount(candidate)}`]"
        @click="selectCandidate(index)"
      >
        {{ candidate }}
      </div>
    </div>
    <div class="zhk-selection__func">
      <button class="zhk-selection__func-btn" @click="closeModal">
        返回
      </button>
    </div>
  </div>
</template>
