// packages/react/src/components/CandidateList.tsx
import React from 'react'
import '../styles/CandidateList.scss'

interface CandidateListProps {
  candidates: string[]
  onSelect: (index: number) => void
}

const CandidateList: React.FC<CandidateListProps> = ({ candidates, onSelect }) => {
  return (
    <div className="zhk-candidate-list">
      {candidates.map((candidate, index) => (
        <button
          key={`candidate-${index}`}
          className="zhk-candidate-list__item"
          onClick={() => onSelect(index)}
        >
          {candidate}
        </button>
      ))}
    </div>
  )
}

export default CandidateList

// packages/vue/src/components/CandidateList.vue
<script setup lang="ts">
import '../styles/CandidateList.scss'

defineProps<{
  candidates: string[]
}>()

const emit = defineEmits<{
  (e: 'select', candidate: string): void
}>()

function handleSelect(candidate: string) {
  emit('select', candidate)
}
</script>

<template>
  <div class="zhk-candidate-list">
    <button
      v-for="(candidate, index) in candidates"
      :key="`candidate-${index}`"
      class="zhk-candidate-list__item"
      @click="handleSelect(candidate)"
    >
      {{ candidate }}
    </button>
  </div>
</template>
