// packages/react/src/components/CandidateBar.tsx
import type { PinyinEngine, PinyinState } from '@zh-keyboard/core'
import type { KeyEvent } from '../types'
import { getPinyinEngine } from '@zh-keyboard/core'
import { forwardRef, useImperativeHandle, useLayoutEffect, useMemo, useRef, useState } from 'react'
import chevronRight from '../assets/icons/chevron-right.svg'
import CandidateList from './CandidateList'
import CandidateSelection from './CandidateSelection'
import '../styles/CandidateBar.scss'

interface CandidateBarProps {
  currentPinyin: string
  onKey: (payload: KeyEvent) => void
  onInput: (text: string) => void
  setCurrentPinyin: (pinyin: string) => void
}

export interface CandidateBarRef {
  handleSelection: (globalIndex: number) => Promise<void>
}

const CandidateBar = forwardRef<CandidateBarRef, CandidateBarProps>(({
  currentPinyin,
  onInput,
  setCurrentPinyin,
}, ref) => {
  const engineRef = useRef<PinyinEngine | null>(null)
  const [engineLoading, setEngineLoading] = useState(true)
  const [pinyinState, setPinyinState] = useState<PinyinState | null>(null)
  const [isSelectionOpen, setIsSelectionOpen] = useState(false)

  const candidates = useMemo(() => pinyinState?.candidates.map(c => c.text) ?? [], [pinyinState])

  const showedPinyin = useMemo(() => {
    if (!pinyinState)
      return ''
    return pinyinState.preeditHead + pinyinState.preeditBody
  }, [pinyinState])

  useImperativeHandle(ref, () => ({
    handleSelection,
  }))

  // 初始化引擎（仅执行一次）
  useLayoutEffect(() => {
    const engine = getPinyinEngine()
    if (!engine) {
      throw new Error('未找到拼音引擎实例，请确保已正确注册引擎')
    }

    engineRef.current = engine
    setEngineLoading(true)

    // 等待引擎真正就绪
    ;(async () => {
      try {
        await engine.whenReady?.()
      } catch (e) {
        console.error('拼音引擎就绪失败:', e)
      }
      setEngineLoading(false)
    })()

    return () => {
      engineRef.current?.syncData?.()
      engineRef.current?.processInput('')?.catch(() => {})
      setEngineLoading(true)
    }
  }, [])

  // 处理拼音变化
  useLayoutEffect(() => {
    const eng = engineRef.current
    if (!eng || engineLoading)
      return

    if (currentPinyin === '') {
      eng.processInput('')?.catch(() => {})
      setPinyinState(null)
      return
    }

    ;(async () => {
      const state = await eng.processInput(currentPinyin)
      setPinyinState(state)
    })()
  }, [currentPinyin, engineLoading])

  async function handleSelection(globalIndex: number) {
    const eng = engineRef.current
    if (!eng)
      return

    const state = await eng.pickCandidate(globalIndex)
    setPinyinState(state)

    if (!state.preeditBody) {
      onInput(state.committed || '')
      setCurrentPinyin('')
      setPinyinState(null)
      setIsSelectionOpen(false)
    }
  }

  if (engineLoading) {
    return (
      <div className="zhk-candidate">
        <div className="zhk-candidate__container zhk-candidate__container--loading">
          <span className="zhk-candidate__loading-text">加载拼音引擎中…</span>
        </div>
      </div>
    )
  }

  return (
    <div className="zhk-candidate">
      <div className="zhk-candidate__container">
        {showedPinyin && (
          <div className="zhk-candidate__pinyin">
            {showedPinyin}
          </div>
        )}
        <div className="zhk-candidate__bottom-container">
          {candidates.length > 0 && (
            <CandidateList
              candidates={candidates}
              onSelect={handleSelection}
            />
          )}
          {candidates.length > 0 && (
            <button
              className="zhk-candidate__more"
              onClick={() => setIsSelectionOpen(true)}
            >
              <img src={chevronRight} alt="更多" />
            </button>
          )}
        </div>
      </div>
      {isSelectionOpen && (
        <CandidateSelection
          candidates={candidates}
          onSelect={handleSelection}
          onClose={() => setIsSelectionOpen(false)}
        />
      )}
    </div>
  )
})

export default CandidateBar

// packages/vue/src/components/CandidateBar.vue
<script setup lang="ts">
import type { PinyinEngine, PinyinState } from '@zh-keyboard/core'
import type { KeyEvent } from '../types'
import { getPinyinEngine } from '@zh-keyboard/core'
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import CandidateList from './CandidateList.vue'
import CandidateSelection from './CandidateSelection.vue'
import '../styles/CandidateBar.scss'

const emit = defineEmits<{
  (e: 'key', payload: KeyEvent): void
  (e: 'input', text: string): void
}>()

const currentPinyin = defineModel<string>({
  required: true,
})

// 拼音引擎实例
let engine: PinyinEngine | null = null

const engineLoading = ref(true)
const pinyinState = ref<PinyinState | null>(null)

const candidates = computed(() => pinyinState.value?.candidates.map(c => c.text) ?? [])

const isSelectionOpen = ref(false)

onMounted(async () => {
  engine = getPinyinEngine()
  if (!engine) {
    throw new Error('未找到拼音引擎实例，请确保已正确注册引擎')
  }

  engineLoading.value = true
  try {
    await engine.whenReady?.()
  } catch (e) {
    console.error('拼音引擎就绪失败:', e)
  }
  engineLoading.value = false

  // 引擎就绪后，若已有拼音输入则立即处理
  if (currentPinyin.value) {
    pinyinState.value = await engine.processInput(currentPinyin.value)
  }
})

onUnmounted(() => {
  engine?.syncData?.()
  engine?.processInput('').catch(() => {})
  engine = null
})

watch(currentPinyin, async (newVal) => {
  const eng = engine
  if (!eng || engineLoading.value)
    return

  if (newVal === '') {
    eng.processInput('').catch(() => {})
    pinyinState.value = null
    return
  }

  pinyinState.value = await eng.processInput(newVal)
})

async function handleSelection(globalIndex: number) {
  if (!engine)
    return

  const state = await engine.pickCandidate(globalIndex)
  pinyinState.value = state

  if (!state.preeditBody) {
    emit('input', state.committed || '')
    currentPinyin.value = ''
    pinyinState.value = null
    isSelectionOpen.value = false
  }
  // 选词后仍有未完成的拼音输入
}

defineExpose({
  handleSelection,
})

const showedPinyin = computed(() => {
  const state = pinyinState.value
  if (!state)
    return ''
  return state.preeditHead + state.preeditBody
})
</script>

<template>
  <div class="zhk-candidate">
    <div v-if="engineLoading" class="zhk-candidate__container zhk-candidate__container--loading">
      <span class="zhk-candidate__loading-text">加载拼音引擎中…</span>
    </div>
    <template v-else>
      <div class="zhk-candidate__container">
        <!-- 输入拼音显示 -->
        <div v-if="showedPinyin" class="zhk-candidate__pinyin">
          {{ showedPinyin }}
        </div>

        <div class="zhk-candidate__bottom-container">
          <!-- 候选词列表 -->
          <CandidateList
            v-if="candidates.length > 0"
            :candidates="candidates"
            @select="handleSelection"
          />
          <button
            v-if="candidates.length > 0"
            class="zhk-candidate__more"
            @click="isSelectionOpen = true"
          >
            <img src="../assets/icons/chevron-right.svg" alt="更多" />
          </button>
        </div>
      </div>
      <CandidateSelection
        v-if="isSelectionOpen"
        :candidates="candidates"
        @select="handleSelection"
        @close="isSelectionOpen = false"
      />
    </template>
  </div>
</template>
