// packages/react/src/components/HandwritingInput.tsx
import type { KeyEvent } from '../types'
import { useElementSize } from '@reactuses/core'
import { CanvasDrawer, getHandwritingRecognizer } from '@zh-keyboard/core'
import React, { useCallback, useLayoutEffect, useRef, useState } from 'react'
import keyboardBackspace from '../assets/icons/keyboard-backspace.svg'
import keyboardReturn from '../assets/icons/keyboard-return.svg'
import { useKeyRepeater } from '../hooks/useKeyRepeater'
import CandidateList from './CandidateList'
import '../styles/HandwritingInput.scss'

interface HandwritingInputProps {
  recognizerInitialized: boolean
  recognizerProgress: number
  onKey: (payload: KeyEvent) => void
  onExit: () => void
}

const HandwritingInput: React.FC<HandwritingInputProps> = ({ recognizerInitialized, recognizerProgress, onKey, onExit }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const containerRef = useRef<HTMLDivElement>(null)
  const canvasDrawer = useRef<CanvasDrawer | null>(null)
  const isRecognizing = useRef(false)
  const [candidates, setCandidates] = useState<string[]>([])

  const { startRepeat, stopRepeat } = useKeyRepeater()

  const recognizeStroke = useCallback(async () => {
    if (!canvasDrawer.current || canvasDrawer.current.getStrokeData().length === 0 || isRecognizing.current)
      return

    const recognizer = getHandwritingRecognizer()
    if (recognizer) {
      isRecognizing.current = true
      try {
        const strokeData = [...canvasDrawer.current.getStrokeData()]
        const results = await recognizer.recognize(strokeData)
        setCandidates(results)
      } catch (error) {
        console.error('识别笔迹失败:', error)
      } finally {
        isRecognizing.current = false
      }
    } else {
      console.warn('手写识别服务不可用')
    }
  }, [])

  const setupCanvas = useCallback(() => {
    if (!canvasRef.current)
      return

    if (canvasDrawer.current) {
      canvasDrawer.current.destroy()
    }

    canvasDrawer.current = new CanvasDrawer(canvasRef.current, {
      onDrawEnd: recognizeStroke,
    })
  }, [recognizeStroke])

  const [_, canvasSize] = useElementSize(containerRef)

  useLayoutEffect(() => {
    if (canvasSize && recognizerInitialized) {
      setupCanvas()
      return () => {
        if (canvasDrawer.current) {
          canvasDrawer.current.destroy()
        }
      }
    }
  }, [canvasSize, recognizerInitialized, setupCanvas])

  function clearCanvas() {
    if (!canvasDrawer.current)
      return
    canvasDrawer.current.clearCanvas()
  }

  function handleSelection(index: number) {
    const candidate = candidates[index]
    if (!candidate)
      return
    onKey({ key: candidate })
    setCandidates([])
    clearCanvas()
  }

  function preventContextMenu(e: React.MouseEvent) {
    e.preventDefault()
  }

  return (
    <div className="handwriting-input">
      <CandidateList candidates={candidates} onSelect={handleSelection} />
      <div ref={containerRef} className="handwriting-content">
        {canvasSize
          ? (
              <>
                <div className="handwriting-buttons">
                  <button
                    className="handwriting-btn handwriting-btn--function"
                    onPointerDown={e => startRepeat(e, () => onKey({ key: '。' }))}
                    onPointerUp={stopRepeat}
                    onPointerLeave={stopRepeat}
                    onPointerCancel={stopRepeat}
                    onContextMenu={preventContextMenu}
                  >
                    。
                  </button>
                  <button
                    className="handwriting-btn handwriting-btn--function"
                    onPointerDown={e => startRepeat(e, () => onKey({ key: '？' }))}
                    onPointerUp={stopRepeat}
                    onPointerLeave={stopRepeat}
                    onPointerCancel={stopRepeat}
                    onContextMenu={preventContextMenu}
                  >
                    ？
                  </button>
                  <button
                    className="handwriting-btn handwriting-btn--function"
                    onPointerDown={e => startRepeat(e, () => onKey({ key: '！' }))}
                    onPointerUp={stopRepeat}
                    onPointerLeave={stopRepeat}
                    onPointerCancel={stopRepeat}
                    onContextMenu={preventContextMenu}
                  >
                    ！
                  </button>
                  <button
                    className="handwriting-btn handwriting-btn--function"
                    onPointerDown={e => startRepeat(e, () => onKey({ key: '、' }))}
                    onPointerUp={stopRepeat}
                    onPointerLeave={stopRepeat}
                    onPointerCancel={stopRepeat}
                    onContextMenu={preventContextMenu}
                  >
                    、
                  </button>
                </div>
                <div className="handwriting-canvas-container">
                  {!recognizerInitialized
                    ? (
                        <div
                          className="handwriting-loading"
                          style={{ width: `${canvasSize}px`, height: `${canvasSize}px` }}
                        >
                          <div className="loading-text">
                            正在加载手写识别...
                          </div>
                          <div className="progress-bar">
                            <div className="progress-fill" style={{ width: `${recognizerProgress * 100}%` }}></div>
                          </div>
                          <div className="progress-text">
                            {Math.round(recognizerProgress * 100)}%
                          </div>
                        </div>
                      )
                    : (
                        <canvas
                          ref={canvasRef}
                          className="handwriting-canvas"
                          width={canvasSize}
                          height={canvasSize}
                        >
                        </canvas>
                      )}
                </div>
                <div className="handwriting-buttons">
                  <button
                    className="handwriting-btn handwriting-btn--function"
                    onPointerDown={e => startRepeat(e, () => onKey({ key: 'delete', isControl: true }))}
                    onPointerUp={stopRepeat}
                    onPointerLeave={stopRepeat}
                    onPointerCancel={stopRepeat}
                    onContextMenu={preventContextMenu}
                  >
                    <img src={keyboardBackspace} alt="删除" />
                  </button>
                  <button
                    className="handwriting-btn handwriting-btn--function"
                    onClick={onExit}
                    onContextMenu={preventContextMenu}
                  >
                    返回
                  </button>
                  <button
                    className="handwriting-btn handwriting-btn--function"
                    onPointerDown={e => startRepeat(e, () => onKey({ key: '，' }))}
                    onPointerUp={stopRepeat}
                    onPointerLeave={stopRepeat}
                    onPointerCancel={stopRepeat}
                    onContextMenu={preventContextMenu}
                  >
                    ，
                  </button>
                  <button
                    className="handwriting-btn handwriting-btn--function"
                    onPointerDown={e => startRepeat(e, () => onKey({ key: 'enter', isControl: true }))}
                    onPointerUp={stopRepeat}
                    onPointerLeave={stopRepeat}
                    onPointerCancel={stopRepeat}
                    onContextMenu={preventContextMenu}
                  >
                    <img src={keyboardReturn} alt="回车" />
                  </button>
                </div>
              </>
            )
          : null}
      </div>
    </div>
  )
}

export default HandwritingInput

// packages/vue/src/components/HandwritingInput.vue
<script setup lang="ts">
import type { KeyEvent } from '../types'
import { useElementSize } from '@vueuse/core'
import { CanvasDrawer, getHandwritingRecognizer } from '@zh-keyboard/core'
import { nextTick, onUnmounted, ref, watchEffect } from 'vue'
import { useKeyRepeater } from '../hooks/useKeyRepeater'
import CandidateList from './CandidateList.vue'
import '../styles/HandwritingInput.scss'

const props = defineProps<{
  recognizerInitialized: boolean
  recognizerProgress: number
}>()

const emit = defineEmits<{
  (e: 'key', payload: KeyEvent): void
  (e: 'exit', payload: void): void
}>()

const canvasRef = ref<HTMLCanvasElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
let canvasDrawer: CanvasDrawer | null = null
// 是否正在识别中
const isRecognizing = ref(false)

// 使用useElementSize获取容器尺寸
const { height: canvasSize } = useElementSize(containerRef)

function clearCanvas() {
  if (!canvasDrawer)
    return
  canvasDrawer.clearCanvas()
}

function setupCanvas() {
  if (!canvasRef.value)
    return

  // 如果已存在画布处理器，先销毁它
  if (canvasDrawer) {
    canvasDrawer.destroy()
  }

  canvasDrawer = new CanvasDrawer(canvasRef.value, {
    onDrawEnd: recognizeStroke,
  })
}

const candidates = ref<string[]>([])

const { startRepeat, stopRepeat } = useKeyRepeater()

// 识别当前笔迹
async function recognizeStroke() {
  if (!canvasDrawer || canvasDrawer.getStrokeData().length === 0 || isRecognizing.value)
    return

  const recognizer = getHandwritingRecognizer()
  if (recognizer) {
    isRecognizing.value = true

    try {
      // 将 readonly array 转换为 mutable array
      const strokeData = [...canvasDrawer.getStrokeData()]
      const results = await recognizer.recognize(strokeData)

      candidates.value = results
    } catch (error) {
      console.error('识别笔迹失败:', error)
    } finally {
      isRecognizing.value = false
    }
  } else {
    console.warn('手写识别服务不可用')
  }
}

// 组件卸载时清理识别器
onUnmounted(() => {
  if (canvasDrawer) {
    canvasDrawer.destroy()
  }
})

watchEffect(() => {
  if (canvasRef.value && canvasSize.value && props.recognizerInitialized) {
    nextTick(() => {
      setupCanvas()
    })
  }
})

function handleSelection(index: number) {
  const candidate = candidates.value[index]
  if (!candidate)
    return
  emit('key', { key: candidate })
  candidates.value = []
  clearCanvas()
}
</script>

<template>
  <div class="handwriting-input">
    <CandidateList
      :candidates
      @select="handleSelection"
    />
    <div ref="containerRef" class="handwriting-content">
      <div class="handwriting-buttons">
        <button
          class="handwriting-btn handwriting-btn--function"
          @pointerdown="(e) => startRepeat(e, () => emit('key', { key: '。' }))"
          @pointerup="stopRepeat"
          @pointerleave="stopRepeat"
          @pointercancel="stopRepeat"
          @contextmenu.prevent
        >
          。
        </button>
        <button
          class="handwriting-btn handwriting-btn--function"
          @pointerdown="(e) => startRepeat(e, () => emit('key', { key: '？' }))"
          @pointerup="stopRepeat"
          @pointerleave="stopRepeat"
          @pointercancel="stopRepeat"
          @contextmenu.prevent
        >
          ？
        </button>
        <button
          class="handwriting-btn handwriting-btn--function"
          @pointerdown="(e) => startRepeat(e, () => emit('key', { key: '！' }))"
          @pointerup="stopRepeat"
          @pointerleave="stopRepeat"
          @pointercancel="stopRepeat"
          @contextmenu.prevent
        >
          ！
        </button>
        <button
          class="handwriting-btn handwriting-btn--function"
          @pointerdown="(e) => startRepeat(e, () => emit('key', { key: '、' }))"
          @pointerup="stopRepeat"
          @pointerleave="stopRepeat"
          @pointercancel="stopRepeat"
          @contextmenu.prevent
        >
          、
        </button>
      </div>
      <div class="handwriting-canvas-container">
        <!-- 进度条显示 -->
        <div
          v-if="!recognizerInitialized"
          class="handwriting-loading"
          :style="{ width: `${canvasSize}px`, height: `${canvasSize}px` }"
        >
          <div class="loading-text">
            正在加载手写识别...
          </div>
          <div class="progress-bar">
            <div class="progress-fill" :style="{ width: `${recognizerProgress * 100}%` }"></div>
          </div>
          <div class="progress-text">
            {{ Math.round(recognizerProgress * 100) }}%
          </div>
        </div>
        <!-- 画布显示 -->
        <canvas
          v-else
          ref="canvasRef"
          class="handwriting-canvas"
          :width="canvasSize"
          :height="canvasSize"
        ></canvas>
      </div>
      <div class="handwriting-buttons">
        <button
          class="handwriting-btn handwriting-btn--function"
          @pointerdown="(e) => startRepeat(e, () => emit('key', { key: 'delete', isControl: true }))"
          @pointerup="stopRepeat"
          @pointerleave="stopRepeat"
          @pointercancel="stopRepeat"
          @contextmenu.prevent
        >
          <img src="../assets/icons/keyboard-backspace.svg" alt="删除" />
        </button>
        <button
          class="handwriting-btn handwriting-btn--function"
          @click="emit('exit')"
          @contextmenu.prevent
        >
          返回
        </button>
        <button
          class="handwriting-btn handwriting-btn--function"
          @pointerdown="(e) => startRepeat(e, () => emit('key', { key: '，' }))"
          @pointerup="stopRepeat"
          @pointerleave="stopRepeat"
          @pointercancel="stopRepeat"
          @contextmenu.prevent
        >
          ，
        </button>
        <button
          class="handwriting-btn handwriting-btn--function"
          @pointerdown="(e) => startRepeat(e, () => emit('key', { key: 'enter', isControl: true }))"
          @pointerup="stopRepeat"
          @pointerleave="stopRepeat"
          @pointercancel="stopRepeat"
          @contextmenu.prevent
        >
          <img src="../assets/icons/keyboard-return.svg" alt="回车" />
        </button>
      </div>
    </div>
  </div>
</template>
