// packages/react/src/components/SymbolKeyboard.tsx
import type { KeyEvent } from '../types'
import React, { useMemo, useState } from 'react'
import lockOpenIconUrl from '../assets/icons/lock-open-outline.svg'
import lockClosedIconUrl from '../assets/icons/lock-outline.svg'
import '../styles/SymbolKeyboard.scss'

interface SymbolKeyboardProps {
  onKey: (payload: KeyEvent) => void
  onExit: () => void
}

const SymbolKeyboard: React.FC<SymbolKeyboardProps> = ({ onKey, onExit }) => {
  const enSymbolStr = '!@#$%^&*(){}[]<>/\\|:;"\',.?+-=_~`€£¥₹©®™°'
  const zhSymbolStr = '！＠＃￥％…＆＊（）｛｝［］＜＞／＼｜：；＂＇，。？＋－＝＿～·€£¥₹©®™°'
  const [symbolType, setSymbolType] = useState('en')
  const currentSymbolStr = useMemo(() => (symbolType === 'zh' ? zhSymbolStr : enSymbolStr), [symbolType])
  const [isLocked, setIsLocked] = useState(false)

  function handleKeyPress(key: string) {
    onKey({ key })
    if (!isLocked) {
      onExit()
    }
  }

  function goBack() {
    onExit()
  }

  function toggleLock() {
    setIsLocked(!isLocked)
  }

  return (
    <div className="symbol-keyboard">
      <div className="symbol-keyboard__content">
        <div className="symbol-keyboard__functions">
          <div className="symbol-keyboard__lang-selector">
            <button
              type="button"
              className={`symbol-keyboard__lang-btn ${
                symbolType === 'zh' ? 'symbol-keyboard__lang-btn--active' : ''
              }`}
              onClick={() => setSymbolType('zh')}
            >
              中文
            </button>
            <button
              className={`symbol-keyboard__lang-btn ${
                symbolType === 'en' ? 'symbol-keyboard__lang-btn--active' : ''
              }`}
              onClick={() => setSymbolType('en')}
            >
              英文
            </button>
          </div>
          <div className="symbol-keyboard__control-group">
            <button
              className={`symbol-keyboard__key symbol-keyboard__key--function symbol-keyboard__key--lock ${
                isLocked ? 'symbol-keyboard__key--locked' : ''
              }`}
              onClick={toggleLock}
            >
              {!isLocked
                ? (
                    <img src={lockOpenIconUrl} alt="Lock open" />
                  )
                : (
                    <img src={lockClosedIconUrl} alt="Lock closed" />
                  )}
            </button>
            <button
              className="symbol-keyboard__key symbol-keyboard__key--function symbol-keyboard__key--back"
              onClick={goBack}
            >
              返回
            </button>
          </div>
        </div>

        <div className="symbol-keyboard__symbols-container">
          <div className="symbol-keyboard__symbols-grid">
            {currentSymbolStr.split('').map(char => (
              <button
                key={`key-${char}`}
                className="symbol-keyboard__key"
                onClick={() => handleKeyPress(char)}
              >
                {char}
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}

export default SymbolKeyboard

// packages/vue/src/components/SymbolKeyboard.vue
<script setup lang="ts">
import type { KeyEvent } from '../types'
import { computed, ref } from 'vue'
import lockOpenIconUrl from '../assets/icons/lock-open-outline.svg'
import lockClosedIconUrl from '../assets/icons/lock-outline.svg'
import '../styles/SymbolKeyboard.scss'

const emit = defineEmits<{
  (e: 'key', payload: KeyEvent): void
  (e: 'exit'): void
}>()

const enSymbolStr = '!@#$%^&*(){}[]<>/\\|:;"\',.?+-=_~`€£¥₹©®™°'
const zhSymbolStr = '！＠＃￥％…＆＊（）｛｝［］＜＞／＼｜：；＂＇，。？＋－＝＿～·€£¥₹©®™°'
const symbolType = ref('en')
const currentSymbolStr = computed(() => symbolType.value === 'zh' ? zhSymbolStr : enSymbolStr)
const isLocked = ref(false)

function handleKeyPress(key: string) {
  emit('key', { key })
  if (!isLocked.value) {
    emit('exit')
  }
}

function goBack() {
  emit('exit')
}

function setSymbolType(type: 'zh' | 'en') {
  symbolType.value = type
}

function toggleLock() {
  isLocked.value = !isLocked.value
}
</script>

<template>
  <div class="symbol-keyboard">
    <div class="symbol-keyboard__content">
      <div class="symbol-keyboard__functions">
        <div class="symbol-keyboard__lang-selector">
          <button
            class="symbol-keyboard__lang-btn"
            :class="{ 'symbol-keyboard__lang-btn--active': symbolType === 'zh' }"
            @click="setSymbolType('zh')"
          >
            中文
          </button>
          <button
            class="symbol-keyboard__lang-btn"
            :class="{ 'symbol-keyboard__lang-btn--active': symbolType === 'en' }"
            @click="setSymbolType('en')"
          >
            英文
          </button>
        </div>
        <div class="symbol-keyboard__control-group">
          <button
            class="symbol-keyboard__key symbol-keyboard__key--function symbol-keyboard__key--lock"
            :class="{ 'symbol-keyboard__key--locked': isLocked }"
            @click="toggleLock"
          >
            <img v-if="!isLocked" :src="lockOpenIconUrl" alt="Lock open" />
            <img v-else :src="lockClosedIconUrl" alt="Lock closed" />
          </button>
          <button
            class="symbol-keyboard__key symbol-keyboard__key--function symbol-keyboard__key--back"
            @click="goBack"
          >
            返回
          </button>
        </div>
      </div>

      <div class="symbol-keyboard__symbols-container">
        <div class="symbol-keyboard__symbols-grid">
          <button
            v-for="(char, index) in currentSymbolStr"
            :key="`key-${index}`"
            class="symbol-keyboard__key"
            @click="handleKeyPress(char)"
          >
            {{ char }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
